const dummy = [
  {
    id: "123",
    testName: "Hussain Sagar",
    type: "Lake",
    deviceId: "",
    kd: "",
    turbidity: "",
    lakeName: "Hussain Sagar",
    salinity: "",
    chlorophyll: "",
    ph: "",
    secchiDepth: "",
    eColi: "",
    date: "",
    status: "Normal",
  },
  {
    id: "234",
    testName: "Apartment",
    type: "Other",
    deviceId: "",
    kd: "",
    turbidity: "",
    lakeName: "Osman Sagar",
    salinity: "",
    chlorophyll: "",
    ph: "",
    secchiDepth: "",
    eColi: "",
    date: "",
    status: "Warning",
  },
  {
    id: "345",
    testName: "Durgam Cheruvu",
    type: "Lake",
    deviceId: "",
    kd: "",
    turbidity: "",
    lakeName: "Durgam Cheruvu",
    salinity: "",
    chlorophyll: "",
    ph: "",
    secchiDepth: "",
    eColi: "",
    date: "",
    status: "Danger",
  },
]

export default dummy